In [1]:
def quicksort(arr):
    if len(arr)<=1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x<pivot]
    middle=[x for x in arr if x==pivot ]
    right=[x for x in arr if x > pivot]
    return quicksort(left)+middle+quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [2]:
x=3
print(type(x))
print(x)
print(x+1)
print(x-1)
print(x*2)
print(x**2)
x+=1
print(x)
x*=2
print(x)
y=2.5
print(type(y))
print(y,y+1,y*2,y**2)


<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [3]:
t =True
f=False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t!=f)

<class 'bool'>
False
True
False
True


In [4]:
hello='hello'
world='world'
print(hello)
print(len(hello))
hw=hello+' '+world
print(hw)
hw12='%s %s %d'%(hello,world,12)
print(hw12)

hello
5
hello world
hello world 12


In [5]:
import os 

s='hello'
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('1','(ell)'))
print('                                world'.strip())

Hello
HELLO
  hello
 hello 
hello
world


In [6]:
xs=[3,1,2]
print(xs,xs[2])
print(xs[-1])
xs[2]='foo'
print(xs)
xs.append('bar')
print(xs)
x= xs.pop()
print(x,xs)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [7]:
nums=list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4]=[8,9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [8]:
animals=['cat','dog','monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [9]:
for idx,animal in enumerate(animals):
    print('#%d:%s'%(idx+1,animal))

#1:cat
#2:dog
#3:monkey


In [10]:
nums=[0,1,2,3,4]
squares=[]
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [11]:
nums = [0,1,2,3,4]
squares=[x**2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [12]:
nums = [0,1,2,3,4]
even_squares = [x**2 for x in nums if x%2 == 0]
print(even_squares)

[0, 4, 16]


In [13]:
d = {'cat':'cute','dog':'furry'}
print(d['cat'])
print('cat' in d)
d['fish']='wet'
print(d['fish'])
print(d.get('monkey','N/A'))
print(d.get('fish','N/A'))
del d['fish']
print(d.get('fish','N/A'))

cute
True
wet
N/A
wet
N/A


In [14]:
d={'person':2,'cat':4,'spider':8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs'%(animal,legs))
    

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [15]:
for animal,legs in d.items():
    print('A %s has %d legs '%(animal,legs))

A person has 2 legs 
A cat has 4 legs 
A spider has 8 legs 


In [16]:
nums=[0,1,2,3,4]
even_num_to_square = {x:x**2 for x in nums if x%2==0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [17]:
animals={'cats','dog'}
print('cat' in animals)
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(len(animals))
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(len(animals))

False
False
True
3
4
3


In [18]:
animals={'cat','dog','fish'}
for idx,animal in enumerate(animals):
    print('#%d:%s'%(idx+1,animal))

#1:cat
#2:dog
#3:fish


In [19]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


In [20]:
d={(x,x+1):x for x in range(10)}
t=(5,6)
print(type(t))
print(d[t])
print(d[(1,2)])

<class 'tuple'>
5
1


In [21]:
def sign(x):
    if x>0:
        return 'positive'
    elif x<0:
        return 'negative'
    else:
        return 'zero'
for x in [-1,-2,0,1,2]:
    print(sign(x))

negative
negative
zero
positive
positive


In [22]:
def hello(name,loud=False):
    if loud:
        print('Hello,%s!'%name.upper())
    else:
        print('Hello,%s'%name)
hello('Bob')
hello('Fred',loud=True)

Hello,Bob
Hello,FRED!


In [23]:
class Greeter(object):
    def __init__(self,name):
        self.name=name
    def greet(self,loud=False):
        if loud:
            print('HELLO,%s!'%self.name.upper())
        else:
            print('Hello,%s'%self.name)


g=Greeter('Fred')
g.greet()
g.greet(loud=True)
        

Hello,Fred
HELLO,FRED!


In [24]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

b= np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [25]:
a = np.zeros((2,2))
print(a)

b=np.ones((1,2))
print(b)

c=np.full((2,2),7)
print(c)

d=np.eye(2)
print(d)

e=np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.56640403 0.81829508]
 [0.99952408 0.66910152]]


In [26]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b=a[:2,1:3]

print(a[0,1])
print(b)

b[0,0]=77
print(a[0,1])

2
[[2 3]
 [6 7]]
77


In [27]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [29]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]
